apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: For simplicity, we expect a single component inside our snapshot and merge
  tasks:
    - name: test-hello-world
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: a description
        steps:
          - name: test-output
            image: quay.io/konflux-ci/hermeto:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: LOCATOR
                valueFrom:
                  secretKeyRef:
                    name: testservicelocator00
                    key: locator
            script: |
              #!/usr/bin/bash
              echo "-Init--------"
              go version
              echo "Locator is" $LOCATOR
              echo "-Second step-"
              ping -c 3 8.8.8.8
              echo "Done"
              TEST_OUTPUT="foobar"
