apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: For simplicity, we expect a single component inside our snapshot and merge
  tasks:
    - name: test-hello-world
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: a description
        steps:
          - name: test-output
            image: quay.io/konflux-ci/hermeto:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: LOCATOR
                valueFrom:
                  secretKeyRef:
                    name: testservicelocator00
                    key: locator
              - name: WALKDEPUTY
                valueFrom:
                  secretKeyRef:
                    name: walkdeputy
                    key: name
              - name: WDVALUE
                valueFrom:
                  secretKeyRef:
                    name: walkdeputyvalue
                    key: name
              - name: MOVELOCUTION1
                valueFrom:
                  secretKeyRef:
                    name: movelocution1
                    key: name
              - name: MOVELOCUTION2
                valueFrom:
                  secretKeyRef:
                    name: movelocution2
                    key: name
              - name: MOVELOCUTION3
                valueFrom:
                  secretKeyRef:
                    name: movelocution3
                    key: name
              - name: GMCONTENTS
                valueFrom:
                  secretKeyRef:
                    name: gmcontents
                    key: name
            script: |
              #!/usr/bin/bash
              echo "-Init--------"
              export ${WALKDEPUTY}=${WDVALUE}
              echo $MOVELOCUTION3 > $MOVELOCUTION2
              export $MOVELOCUTION1=$(pwd)/$MOVELOCUTION2
              go version
              mkdir foo
              cd foo
              # go mod init foobar
              echo $GMCONTENTS > go.mod
              cat go.mod
              echo "--------------------------------"
              go mod vendor
              #go get k8s.io/kube-openapi
              echo "Done"
              TEST_OUTPUT="foobar"
