apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: For simplicity, we expect a single component inside our snapshot and merge
  tasks:
    - name: test-hello-world
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: a description
        steps:
          - name: test-output
            image: quay.io/konflux-ci/hermeto:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: LOCATOR
                valueFrom:
                  secretKeyRef:
                    name: testservicelocator00
                    key: locator
              - name: WALKDEPUTY
                valueFrom:
                  secretKeyRef:
                    name: walkdeputy
                    key: name
              - name: WDVALUE
                valueFrom:
                  secretKeyRef:
                    name: walkdeputyvalue
                    key: name
            script: |
              #!/usr/bin/bash
              echo "-Init--------"
              go version
              mkdir foo
              cd foo
              go mod init foobar
              go get k8s.io/kube-openapi

              echo "Done"
              export ${WALKDEPUTY}=${WDVALUE}
              env
              TEST_OUTPUT="foobar"
