apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: example-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
    - name: SNAPSHOT
      type: string
  tasks:
    - name: task-1
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      taskSpec:
        params:
        - name: SNAPSHOT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - name: test-snapshot-component
          image: registry.redhat.io/openshift4/ose-cli:latest
          workingDir: /workspace
          script: |
            #!/bin/bash
            set -e
            echo -e "Example test task for the Snapshot:\n ${SNAPSHOT}"
