apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: For simplicity, we expect a single component inside our snapshot and merge
  tasks:
    - name: test-hello-world
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: a description
        steps:
          - name: test-output
            image: quay.io/konflux-ci/hermeto:latest
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: FOOBAR
                value: "$(params.FOOBARBAZ)"
            script: |
              #!/usr/bin/bash
              echo "Did something"
              go version
              echo "Foobar is" $FOOBAR
              env
              echo "---------"
              echo $(params.FOOBARBAZ)
              echo "Done"
              TEST_OUTPUT="foobar"
